image: microsoft/dotnet:sdk

options:
  max-time: 2

pipelines:
  branches:
    '{master,dev}':
        - step:
            caches:
              - dotnetcore
            script: 
              - dotnet restore src/RecruitMe.sln
              - dotnet build src/RecruitMe.sln -c Release  
              - dotnet test src/RecruitMe.sln -c Release
